### ISSUE TITLE
デザイン変更

### ISSUE THREAD

**Issue by sasaco** [structuralengine/structuralengine.com#26]
## 以下の４ページの作成

▼ログイン用ページ
https://orchidhorse13.sakura.ne.jp/formal.component.html
▼ログイン後のトップページ
https://orchidhorse13.sakura.ne.jp/stripe.component.html
▼パスワード再発行ページ
https://orchidhorse13.sakura.ne.jp/forgot.password.html
▼サインアップページ
https://orchidhorse13.sakura.ne.jp/sign.up.html

### 現状の masterブランチの状態

現状 masterブランチは、下図に示す**昔のページ**で示す部分のソースファイルがあります。

https://miro.com/app/board/o9J_lM0y_yY=/?share_link_id=217364249814

### _old\stripe.component を参考にして

上記の４ページを以下の名称で作成してください
- /top
- /forgot
- /mypage
- /signup

## html と css があります

デザイン案は、docs フォルダに  html と css がありますんので使ってください

**Comment by sasaco** [comment]
## src\environments\environment.ts

このファイルがないと動作しないので、作業者は取りに来てください
![image](https://user-images.githubusercontent.com/4043298/210511386-2644fef9-c93f-4810-adbe-eb1c9ac61886.png)

**Comment by yuluji** [comment]
【memo】
/top
/forgot
/mypage
/signup
等の表記はそれぞれ、アドレスの末尾を表す
